config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :competences, except: [:show]

  root to: 'competences#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competence.rb
class Competence < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { maximum: 255 }

  def self.search(search_string=nil)
    if search_string
      where('name like ?', "%#{search_string}%")
    else
      all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    competences_path
  end

  def after_sign_out_path_for(resource_or_scope)
    competences_path
  end

end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController
  before_action :get_current, only: [ :edit, :update, :destroy ]

  helper_method :sort_param, :direction_param, :safe_params

  # respond_to :html, :js, :json

  def index
    @competences = Competence.search(params[:search]).order("#{sort_param} #{direction_param}").paginate(per_page: 5, page: params[:page])
    respond_to do |format|
      format.js { render layout: false }
      format.html { render :index }
    end
  end

  def new
    @competence = Competence.new
  end

  def create
    @competence = Competence.new competence_params
    respond_to do |format|
      if @competence.save
        format.html { redirect_to competences_path, notice: 'Создана новая компетенция' }
        format.json { render :index, status: :created, location: competences_path }
      else
        format.html { render :new }
        format.json { render json: @competence.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @competence.update competence_params
        format.html { redirect_to competences_path, notice: 'Обновлена компетенция' }
        format.json { render :index, status: :ok, location: competences_path }
      else
        format.html { render :new }
        format.json { render json: @competence.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    respond_to do |format|
      if @competence.destroy
        format.html { redirect_to competences_path, notice: 'Удаление прошло успешно' }
        format.json { render :index, status: :ok, location: competences_path }
      else
        format.html { render :index, error: 'Не получилось удалить компетенцию' }
        format.json { render @competence.errors, status: :unprocessable_entity  }
      end
    end
  end

private
  def competence_params
    params.require(:competence).permit(:name)
  end

  def get_current
    @competence = Competence.find params[:id]
  end

  # По какому полю сортируем, на будущее
  def sort_param
    Competence.column_names.include?(params[:sort])? params[:sort] : 'name'
  end

  def direction_param
    %w(asc desc).include?(params[:direction])? params[:direction] : 'asc'
  end

  # См. https://github.com/rails/rails/issues/26289
  def safe_params
    params.except(:host, :port, :protocol).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competences_helper.rb
module CompetencesHelper
  def rails_to_bootstrap_type(type)
    case type
      when 'error'
        'alert-danger'
      when 'notice'
        'alert-info'
      else
        type
    end

  end

  def show_message(type, message)
    content_tag( :div,
                link_to("&times;".html_safe, '#', class: 'close', data: { dismiss: 'alert' }, aria: { label: 'close' }) +
                message,
                class: 'alert fade in '+rails_to_bootstrap_type(type) )
  end

  # Взято по примеру с http://railscasts.com/episodes/228-sortable-table-columns?autoplay=true
  # Возвращает ссылку, содержащую нужные параметры для пагинации и сортировки, а также правильное направление сортировки
  # Направление сортировки меняется на убывание, если было по возрастанию и кликнули на тот же столбец
  # @param column - столбец из модели, по которому сортируем
  # @param title - Наименование, которое выводим в заголовке таблице, которое кликабельно
  def sortable(column, title = nil)
    title ||= column
    css_bootstrap_class = 'glyphicon '
    css_bootstrap_class += (direction_param == 'asc')? 'glyphicon-arrow-up':'glyphicon-arrow-down'
    direction = ( column == sort_param && direction_param == 'asc' )? 'desc' : 'asc'
    link_to title, safe_params.merge( sort: column, direction: direction, page: nil ), class: css_bootstrap_class, remote: true
  end

  # https://gist.github.com/jeroenr/3142686
  def ajax_paginate(collection, params={})
    will_paginate collection, params.merge(renderer: RemoteLinkPaginationHelper::LinkRenderer)
  end
end

app/helpers/remote_link_pagination_helper.rb
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes)
      attributes['data-remote'] = true
      super
    end
  end
end

app/views/competences/_competence.slim
tr
  td = competence.name
  td
    = link_to content_tag(:span, '', class: 'glyphicon glyphicon-edit control-actions', title: 'Редактировать'), edit_competence_path(competence)
    = link_to content_tag(:span, '', class: 'glyphicon glyphicon-trash', title: 'Удалить'), competence, method: :delete, data: { confirm: 'Вы уверены?' }

app/views/competences/_competences.slim
table.table.table-hover
  thead
    tr
      th = sortable 'name', 'Наименование'
      th Действия
  tbody
    = render @competences

div.apple_pagination
  = ajax_paginate @competences

app/views/competences/_form.slim
= form_for @competence, role: :form do |f|
  div.form-group
    = f.label :name, 'Введите название компетенции'
    = f.text_field :name, class: 'form-control'

  div.form-group
    = f.submit class: 'btn btn-info'

app/views/competences/_search.slim
= form_for(competences_path, method: :get, html: { id: 'competences-search-form', role: 'form', class: 'form-inline' }, remote: true ) do
  div.form-group
    = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Введите название компетенции'
    = button_tag '', class: 'glyphicon glyphicon-search', title: 'Поиск по компетенции'

app/views/competences/edit.slim
h2 Редактирование компетенции
= render 'form'

app/views/competences/index.js.erb
$('div#competences-list').empty().append('<%= j render 'competences' %>');

app/views/competences/index.slim
h2 Список компетенций
= render 'search'
= link_to 'Создать', new_competence_path, class: 'btn btn-info pull-right'

= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]

div#competences-list
  = render 'competences'

app/views/competences/new.slim
h2 Создание новой компетенции
= render 'form'

app/views/layouts/_alerts.slim
div.container-fluid
  div.row
    div.col-lg-6.col-lg-offset-1
      - flash.each do |type, message|
        = show_message type, message

app/views/layouts/_navbar.slim
nav.navbar.navbar-inverse
  ul.nav.navbar-nav
    li.active
      = link_to 'Компетенции', competences_path
    - unless signed_in?
      li
        = link_to 'Войти', new_user_session_path
      li
        = link_to 'Регистрация', new_user_registration_path
    - else
      li
        = link_to 'Выйти', destroy_user_session_path, method: :delete

app/views/layouts/application.slim
doctype html
html
  head
    title ПрофПорт
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/navbar'
    = render 'layouts/alerts'
    div.container-fluid
      div.row#main-frame
        div.col-lg-7.col-lg-offset-1
          = yield